### ISSUE TITLE
runtime panic issue with 0.3.0 release

### ISSUE THREAD

**Issue by chenrui333** [im2nguyen/rover#87]
Still have some issue with running rover in my local

### How to reproduce

- grab the artifact from [releases page](https://github.com/im2nguyen/rover/releases/tag/v0.3.0)
- create `main.tf`
- run `rover_0.3.0_darwin_arm64/rover_v0.3.0 -standalone -tfPath <path-to-terraform-installation>`

#### main.tf ref

```tf
output "hello_world" {
  value = "Hello, World!"
}
```

### error log
```sh
2022/01/24 14:25:15 Starting Rover...
2022/01/24 14:25:15 Initializing Terraform...
2022/01/24 14:25:15 Generating plan...
2022/01/24 14:25:15 Generating resource overview...
open .terraform/modules/modules.json: no such file or directory
2022/01/24 14:25:15 Generating resource map...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0xb0 pc=0x10302d520]

goroutine 1 [running]:
main.(*rover).GenerateModuleMap(0x1400000b320, 0x140003c9b68, {0x0, 0x0})
	rover/map.go:103 +0x1e0
main.(*rover).GenerateMap(0x1400000b320)
	rover/map.go:322 +0x1c8
main.(*rover).generateAssets(0x1400000b320)
	rover/main.go:193 +0x10c
main.main()
	rover/main.go:138 +0xeb8
```

**Comment by im2nguyen** [comment]
@JackFlukinger

**Comment by JackFlukinger** [comment]
@im2nguyen I'll check this out later today :)

**Comment by chenrui333** [comment]
> @chenrui333 can you provide an example of what your configuration looks like or a way to replicate this error? This would make the debugging process easier. Thank you!

The how to reproduce covers what I have (I am probably using the default config)

**Comment by im2nguyen** [comment]
I just created a new release with the changes that @JackFlukinger implemented (thanks!)

once the new release is built (~10 mins), can you test it? thanks for reporting and testing out rover!

**Comment by chenrui333** [comment]
This is the error right now

```
$ /Users/rui/Downloads/rover/rover_v0.3.0  -standalone -tfPath /opt/homebrew/opt/terraform/bin/terraform
Killed: 9
```

**Comment by JackFlukinger** [comment]
Hey @chenrui333 , haven't seen that error before. I think that might be something on your end -- I just downloaded and tested with the binary you're using, seems to work properly. Your configuration is still just the output, correct?
